{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlimit.fullname" . }}
  labels:
    {{- include "openlimit.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets }}
  {{- if .databaseUrl }}
  database-url: {{ .databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .adminBearerToken }}
  admin-bearer-token: {{ .adminBearerToken | b64enc | quote }}
  {{- end }}
  {{- if .openaiApiKey }}
  openai-api-key: {{ .openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .anthropicApiKey }}
  anthropic-api-key: {{ .anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .kmsStaticKey }}
  kms-static-key: {{ .kmsStaticKey | b64enc | quote }}
  {{- end }}
  {{- if .vaultToken }}
  vault-token: {{ .vaultToken | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
